
TRACKING:
    # TRACKER PARAMETERS
    EXAMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    LOST_INSTANCE_SIZE: 768 # original value is 831
    WINDOW_INFLUENCE: 0.35
    LOST_WINDOW_INFLUENCE: 0
    LOST_THRESHOLD: 0.5
    
    
KALMAN: 
    # KALMAN PARAMETERS
    KALMAN_RATIO: 0.7
    MEASUREMENT_XY_STD: 5
    MEASUREMENT_WH_STD: 10
    PROCESS_STD: 1
    
TRACKLET: 

    TRACKLET_SIZE: 30
    
REID: 
    # REID PARAMETERS
    REID_INSTANCE_SIZE: 128
    BACKBONE: 'resnet18'

DETECTION: 
    
    


